apiVersion: v1
kind: Service
metadata:
  name: mesician-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: mesician-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
