apiVersion: v1
kind: Service
metadata:
  name: mesician-minio
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: mesician-minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
